name: Tebex-PMMP
main: tebexio\pocketmine\TebexPlugin
version: 3.0.0
author: Tebex Limited
api: 3.0.0
api-version: 3.0.0
permissions:
  buycraft.admin:
    default: op
    children:
      tebex.admin:
        default: op
